---
# SPDX-FileCopyrightText: NONE
# SPDX-License-Identifier: CC0-1.0

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "com.github.hierynomus.license-report"
      - dependency-name: "com.github.spotbugs"
