---
# SPDX-FileCopyrightText: NONE
# SPDX-License-Identifier: CC0-1.0

coverage:
  status:
    project:
      default:
        threshold: 10%
    patch:
      default:
        threshold: 20%

comment: false
