---
# SPDX-FileCopyrightText: (c) 2022 ale5000
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileType: SOURCE
name: "Release"
permissions: {}
on:
  push:
    tags:
      - "v*"
jobs:
  base-job:
    name: "Release"
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: "Check out code"
        uses: actions/checkout@v4
      - name: "Set up Java"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: "Build"
        shell: bash
        run: |
          ### Building...
          workspace_path='${{ github.workspace }}'; readonly workspace_path
          "${workspace_path:?}/gradlew" clean buildOtaOSS
      - name: "Upload release"
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          # artifactErrorsFailBuild: true
          # artifacts: "output/*.zip*"
          body: "See the full [**changelog**](./CHANGELOG.rst)."
          replacesArtifacts: false
